@startuml TdmContainer_2.0.0-tsi.240104.1855+diagram.completeness
skinparam responseMessageBelowArrow true

title
TdmContainer_2.0.0-tsi.240104.1855+testcase.completeness
end title

participant "Postman" as Postman
participant "Data" as Data
participant "Collection" as Collection

participant "/control-construct?fields=..." as ListOfLTPUuidAndLidPairsAndNames

participant "/tdm-container-capability" as Capability
participant "/tdm-container-configuration" as Configuration
participant "/tdm-container-status" as Status

group Preparation
  Data --\\o Postman : {servers,\n   mountName,\n   kindOfReference,\n   suffixUrlEncodingIsRequired}
  activate Postman
  Postman --\\o Collection : {servers,\n   mountName,\n   kindOfReference,\n   suffixUrlEncodingIsRequired}

  Collection --\\o Postman : {servers, mountName}
  Postman -> ListOfLTPUuidAndLidPairsAndNames : {mountName}
  Postman <-- ListOfLTPUuidAndLidPairsAndNames : {(uuid, localId, layerProtocolName)}
  note right Postman
    selection of TdmContainer
  end note
  Postman --\\o Collection : {uuid, localId}
end

group /tdm-container-capability
  Collection --\\o Postman : {mountName, uuid, localId}
  Postman -> Capability : {mountName, uuid, localId}
  Postman <-- Capability : {CapabilityClass}
  note right Postman
    schema validation
  end note
end

group /tdm-container-configuration
  Collection --\\o Postman : {mountName, uuid, localId}
  Postman -> Configuration : {mountName, uuid, localId}
  Postman <-- Configuration : {ConfigurationClass}
  note right Postman
    schema validation
  end note
end

group /tdm-container-status
  Collection --\\o Postman : {mountName, uuid, localId}
  Postman -> Status : {mountName, uuid, localId}
  Postman <-- Status : {StatusClass}
  note right Postman
    schema validation
  end note
end

deactivate Postman

@enduml